# 
name: hu-pbl-workshop
channels: 
  - conda-forge
dependencies:
  - python=3.7
  #
  - cartopy
  - hdf5
  - hvplot  # brings holoviews, bokeh
  - ipywidgets
  - jupyter_contrib_nbextensions
  - matplotlib
  - metpy
  - netcdf4
  - numpy
  - pandas
  - pvlib-python
  - rise  # for slides
  - scikit-learn
  - scipy
  - seaborn
  - siphon  # Unidata data downloader
  - statsmodels
  - xarray
